<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>AI Analysis Report - {{ $design->name }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }

        .header {
            background-color: #1a1a1a;
            color: #fff;
            padding: 40px 20px;
            text-align: center;
        }

        .header h1 {
            margin: 0;
            font-size: 28px;
            letter-spacing: 1px;
        }

        .header p {
            margin: 5px 0 0;
            opacity: 0.8;
            font-size: 14px;
        }

        .container {
            padding: 30px;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-title {
            font-size: 20px;
            font-weight: bold;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
            margin-bottom: 20px;
            color: #1a1a1a;
        }

        .score-card {
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
            border: 1px solid #dee2e6;
        }

        .score-value {
            font-size: 48px;
            font-weight: bold;
            color: #d97706;
        }

        .score-label {
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .summary-box {
            font-style: italic;
            color: #4b5563;
            background: #fffbeb;
            border-left: 4px solid #f59e0b;
            padding: 15px 20px;
            margin: 20px 0;
        }

        .finding-item {
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 1px dashed #eee;
        }

        .finding-meta {
            margin-bottom: 8px;
        }

        .severity {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .severity-high {
            background-color: #fee2e2;
            color: #b91c1c;
        }

        .severity-medium {
            background-color: #fef3c7;
            color: #92400e;
        }

        .severity-low {
            background-color: #d1fae5;
            color: #065f46;
        }

        .finding-issue {
            font-weight: bold;
            font-size: 16px;
            color: #111827;
        }

        .finding-recommendation {
            margin-top: 5px;
            color: #059669;
            font-size: 14px;
        }

        .wow-factor {
            background: linear-gradient(135deg, #fef3c7 0%, #fffbeb 100%);
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #fbbf24;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #999;
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #eee;
        }

        .design-link {
            color: #2563eb;
            text-decoration: none;
        }

        .thumbnail {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            margin-top: 15px;
            border: 1px solid #eee;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>DESIGN AUDIT REPORT</h1>
        <p>Generated by UIPulse AI Intelligence</p>
    </div>

    <div class="container">
        <div class="section">
            <div class="section-title">Design Information</div>
            <table style="width: 100%;">
                <tr>
                    <td style="width: 50%;">
                        <strong>Name:</strong> {{ $design->name }}<br>
                        <strong>Project:</strong> {{ $design->project->name }}<br>
                        <strong>Type:</strong> {{ ucfirst(str_replace('_', ' ', $analysis->type)) }}
                    </td>
                    <td style="width: 50%; text-align: right;">
                        <strong>Date:</strong> {{ $analysis->created_at->format('M d, Y') }}<br>
                        <strong>Source:</strong> <a href="{{ $design->figma_url }}" class="design-link">Figma File</a>
                    </td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="score-card">
                <div class="score-label">Overall Health Score</div>
                <div class="score-value">{{ $results['score'] ?? 'N/A' }}%</div>
                @if(isset($results['summary']))
                    <div class="summary-box">
                        "{{ $results['summary'] }}"
                    </div>
                @endif
            </div>
        </div>

        @if(!empty($results['findings']))
            <div class="section">
                <div class="section-title">Critical Findings & Recommendations</div>
                @foreach($results['findings'] as $finding)
                    <div class="finding-item">
                        <div class="finding-meta">
                            <span class="severity severity-{{ $finding['severity'] ?? 'low' }}">
                                {{ $finding['severity'] ?? 'LOW' }}
                            </span>
                        </div>
                        <div class="finding-issue">{{ $finding['issue'] ?? 'No issue description provided.' }}</div>
                        <div class="finding-recommendation">
                            <strong>Fix:</strong> {{ $finding['recommendation'] ?? 'No recommendation provided.' }}
                        </div>
                    </div>
                @endforeach
            </div>
        @endif

        @if(isset($results['wow_factor']))
            <div class="section">
                <div class="wow-factor">
                    <strong style="color: #92400e; display: block; margin-bottom: 5px;">✨ THE WOW FACTOR</strong>
                    {{ $results['wow_factor'] }}
                </div>
            </div>
        @endif

        @if(isset($results['generated_image_url']))
            <div class="section">
                <div class="section-title">Visual Fix Mockup</div>
                <p style="font-size: 13px; color: #666; margin-bottom: 15px;">Targeted visual improvement generated by AI
                    (DALL-E):</p>
                <img src="{{ $results['generated_image_url'] }}" class="thumbnail" alt="Visual Fix">
            </div>
        @endif

        <div class="footer">
            &copy; {{ date('Y') }} UIPulse. This report was generated automatically via AI Analysis.
        </div>
    </div>
</body>

</html>